/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#00a572',
        'on-secondary-fixed-variant': '#005236',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'surface-container-highest': '#31353f',
        'surface-variant': '#31353f',
        'surface-dim': '#0f131c',
        tertiary: '#ddb7ff',
        'on-tertiary-container': '#400071',
        outline: '#8c909f',
        'on-error': '#690005',
        primary: '#adc6ff',
        'tertiary-fixed-dim': '#ddb7ff',
        'on-surface-variant': '#c2c6d6',
        'on-tertiary': '#490080',
        'on-secondary-fixed': '#002113',
        'secondary-fixed-dim': '#4edea3',
        'tertiary-fixed': '#f0dbff',
        'on-secondary-container': '#00311f',
        'on-tertiary-fixed-variant': '#6900b3',
        secondary: '#4edea3',
        'on-tertiary-fixed': '#2c0051',
        'primary-container': '#4d8eff',
        'surface-container': '#1c1f29',
        'outline-variant': '#424754',
        'primary-fixed-dim': '#adc6ff',
        'on-secondary': '#003824',
        'on-primary': '#002e6a',
        'surface-bright': '#353943',
        'surface-tint': '#adc6ff',
        'on-background': '#dfe2ef',
        'inverse-primary': '#005ac2',
        'secondary-fixed': '#6ffbbe',
        'surface-container-low': '#181b25',
        'error-container': '#93000a',
        background: '#0f131c',
        surface: '#0f131c',
        error: '#ffb4ab',
        'tertiary-container': '#b76dff',
        'primary-fixed': '#d8e2ff',
        'on-surface': '#dfe2ef',
        'surface-container-high': '#262a34',
        'inverse-on-surface': '#2c303a',
        'inverse-surface': '#dfe2ef',
        'surface-container-lowest': '#0a0e17',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#00285d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '380px',
        'margin-desktop': '32px',
        'container-max': '1440px',
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg': ['Geist'],
        'headline-md': ['Geist'],
        display: ['Geist'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        mono: ['Geist'],
        'label-sm': ['Geist'],
        'label-md': ['Geist'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        mono: ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      letterSpacing: {
        tighter: '-0.02em',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}